[package]
name = "repoblame"
version = "0.0.1"
edition = "2021"


[dependencies]
bytelines = "2.5.0"
clap = { version = "4.5.4", features = ["derive"] }
content_inspector = "0.2.4"
# git2 = "0.18.3"
tabled = "0.15.0"
thousands = "0.2.0"

[profile.release]
lto = "thin"
